"""Create a content-versioned, atomic offline cache for a Flutter release build."""
import hashlib
import json
from pathlib import Path

root = Path(__file__).resolve().parents[1] / 'build/web'
required = ['index.html', 'main.dart.js', 'ocr/tesseract.min.js', 'ocr/worker.min.js',
            'ocr/tesseract-core.wasm.js', 'ocr/tesseract-core.wasm', 'ocr/eng.traineddata.gz']
for name in required:
    if not (root / name).is_file():
        raise SystemExit(f'Missing {name}; download OCR assets and build first.')
# Never install Flutter legacy worker: we own caching and its lifecycle.
legacy = root / 'flutter_service_worker.js'
legacy.unlink(missing_ok=True)
files = sorted(p for p in root.rglob('*') if p.is_file() and p.name != 'meter-sw.js'
               and p.suffix not in ('.map',))
paths = [p.relative_to(root).as_posix() for p in files]
version = hashlib.sha256(b''.join(name.encode() + hashlib.sha256(p.read_bytes()).digest()
                                 for name, p in zip(paths, files))).hexdigest()[:20]
script = '''// Generated by tool/prepare_offline.py. Do not edit.
const CACHE = 'fieldnote-VERSION';
const FILES = FILE_LIST;
const absolute = name => new URL(name, self.registration.scope).href;
self.addEventListener('install', event => event.waitUntil((async () => {
  const cache = await caches.open(CACHE);
  try {
    // Small batches avoid a large simultaneous download on mobile.
    for (let i = 0; i < FILES.length; i += 4) {
      await cache.addAll(FILES.slice(i, i + 4).map(name => new Request(absolute(name), {cache: 'reload'})));
    }
    await cache.put(absolute('__offline_complete__'), new Response('ready'));
  } catch (error) {
    await caches.delete(CACHE);
    throw error;
  }
  // New versions activate on the next full app close/reopen, avoiding mixed assets.
})()));
self.addEventListener('activate', event => event.waitUntil((async () => {
  await self.clients.claim();
  for (const key of await caches.keys()) {
    if (key.startsWith('fieldnote-') && key !== CACHE) await caches.delete(key);
  }
})()));
self.addEventListener('fetch', event => {
  if (event.request.method !== 'GET' || !event.request.url.startsWith(self.registration.scope)) return;
  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const cached = await cache.match(event.request, {ignoreSearch: true});
    if (cached) return cached;
    if (event.request.mode === 'navigate') return cache.match(absolute('index.html'));
    return fetch(event.request);
  })());
});
self.addEventListener('message', event => {
  if (event.data !== 'CHECK_READY' || !event.ports[0]) return;
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    const complete = await cache.match(absolute('__offline_complete__'));
    const entries = await Promise.all(FILES.map(name => cache.match(absolute(name))));
    event.ports[0].postMessage({ready: Boolean(complete) && entries.every(Boolean)});
  })());
});
'''.replace('VERSION', version).replace('FILE_LIST', json.dumps(paths))
(root / 'meter-sw.js').write_text(script)
print(f'Offline build {version}: {len(paths)} assets, {sum(p.stat().st_size for p in files) / 1048576:.1f} MiB')
